#NumPY-travis oliphant 2005

In [10]:
import numpy as np
l=[1,2,4,5,6]
a=np.array(l)
print(a)
print(type(a))
print(a.size)


[1 2 4 5 6]
<class 'numpy.ndarray'>
5


In [3]:
import numpy as np
l=[[1,2,4],[2,4,5],[9,5,5]]
a=np.array(l)
print(type(a))
print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.itemsize)

<class 'numpy.ndarray'>
(3, 3)
2
int32
4


In [19]:
l=[1,2]
print(type(l))

<class 'list'>


In [27]:
ar=np.array([1,2,3,8,4])
p=ar[1:3]
print(p)

print(ar[::-1])

ar[1]=999
print(ar)

ar[0:3]=11
print(ar)

print(ar.view())

[2 3]
[4 8 3 2 1]
[  1 999   3   8   4]
[11 11 11  8  4]
[11 11 11  8  4]


In [44]:
ar=np.array([2,3,4,5,6,7,8,4,2])
print(ar.reshape(3,3))
print(np.arange(10))
ar.resize(2,9)
print(ar)

[[2 3 4]
 [5 6 7]
 [8 4 2]]
[0 1 2 3 4 5 6 7 8 9]
[[2 3 4 5 6 7 8 4 2]
 [0 0 0 0 0 0 0 0 0]]


In [4]:
import numpy as np
ar=np.arange(10)
print(ar)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
a=[1,2,4+1j]
ar=np.array(a)
print(a)
print(type(ar))
print(ar.dtype)

[1, 2, (4+1j)]
<class 'numpy.ndarray'>
complex128


In [13]:
a=[1,2,3,4,5]
n=np.append(a,[8,9])
print(n)
ar1=np.insert(n,2,12)
print(ar1)

[1 2 3 4 5 8 9]
[ 1  2 12  3  4  5  8  9]


In [17]:
l=[1,2,3,4]
l[0]=10
print(l)

[10, 2, 3, 4]


In [18]:
ar1[0:3]=100
print(ar1)

[100 100 100   3   4   5   8   9]


In [21]:
aa=ar1.reshape(4,2)
print(aa)

[[100 100]
 [100   3]
 [  4   5]
 [  8   9]]


In [24]:
print(len(aa))

4


In [32]:
arr=np.zeros(10).reshape(5,2)
print(arr)
ar1=np.array(arr,dtype="int")
print(ar1)
ar1=np.array(arr,dtype="complex128")
print(ar1)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
[[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]


In [28]:
arr=np.ones(10).reshape(5,2)
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [43]:
l=[[1,2,4],[2,4,5],[9,5,5]]
a=np.array(l)
print(a[0,1])
print(sum(a))
print(sum(a[0]))
print(a.sum(axis=1))


2
[12 11 14]
7
[ 7 11 19]


In [48]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a.dot(b))
print(b.dot(a))

[[19 22]
 [43 50]]
[[23 34]
 [31 46]]


In [58]:
ar=np.eye(3)
print(ar)
np.fill_diagonal(np.fliplr(ar),[1,2,3])
print(ar)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 1.]
 [0. 2. 0.]
 [3. 0. 1.]]


In [59]:
ar=np.eye(3)
print(ar)
np.fill_diagonal(np.flip(ar),[1,2,3])
print(ar)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[3. 0. 0.]
 [0. 2. 0.]
 [0. 0. 1.]]


In [60]:
ar=np.eye(3)
print(ar)
np.fill_diagonal(np.flipud(ar),[1,2,3])
print(ar)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 3.]
 [0. 2. 0.]
 [1. 0. 1.]]
